repos:
    # python import sorting - will amend files
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.1.0
      hooks:
          - id: isort

    # python code formatting - will amend files
    - repo: https://github.com/ambv/black
      rev: 19.10b0
      hooks:
          - id: black

    # PEP8 linting, with added Django goodness, and custom YJ plugin
    - repo: https://github.com/pre-commit/mirrors-pylint
      rev: v2.5.3
      hooks:
          - id: pylint
            additional_dependencies: ["pylint_django"]

    # Flake8 includes pyflakes, pycodestyle, mccabe, pydocstyle, bandit
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.3
      hooks:
          - id: flake8
            additional_dependencies: ["flake8-docstrings", "flake8-bandit"]
            exclude: ^tests

    # python static type checking
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.782
      hooks:
          - id: mypy
            exclude: ^tests

    # JS, JSON and SCSS formatting
    - repo: https://github.com/prettier/prettier
      rev: 2.0.5
      hooks:
          - id: prettier
